### ISSUE TITLE
Wifi?

### ISSUE THREAD

**Issue by pipy71** [M5ez/Core2ez#11]
Hi Rob

First of all, I want to say a BIG THANKYOU for all your efforts in producing this library.
I love the keyboard input, it's going to be awesome to enter a WiFi password this way!

I have noticed that the ezWifi.h src is commented out, is this not yet working?

Thanks!

**Comment by ropg** [comment]
ezWifi is still in development. In fact, it is what I wam working on right now, together with a screen header and some other features from the original M5ez. Stay tuned..

**Comment by ropg** [comment]
OK, try the WifiAndHeader example...

(It's all pretty rough still)

**Comment by koenvervloesem** [comment]
Is Wi-Fi already working? When I run the `menus` example and I click on **Wifi Settings**, **Join a network** and then **Scan and join**, the scan results in a list of three empty menu items and one with one of my access points. When I press on the latter, it just returns to the **Join a network** menu without asking for my access point's password.

**Comment by ropg** [comment]
> Is Wi-Fi already working? When I run the menus example and I click on Wifi Settings, Join a network and then Scan and join, the scan results in a list of three empty menu items and one with one of my access points. When I press on the latter, it just returns to the Join a network menu without asking for my access point's password.


No, it's not working yet. I need to get back to another project for the next few weeks, but will be on it right after that...


Rop
