### ISSUE TITLE
colors in ezWindow do not work

### ISSUE THREAD

**Issue by digi-thomas2003** [M5ez/Core2ez#13]
Hello Rop,

in my sketch I defined a window with this color scheme:
`ezWindow dateInfo( 0,  30, 320, 180, {BLACK, GREEN, NODRAW});`

As far as I understand, the background should be black, the text green and no outline.
But: The text in this window is still white. I can only change it using
`dateInfo.setTextColor(GREEN);`

Can you please check this?

Thank you very much!!
Best regards
Tom

**Comment by ropg** [comment]
The text color for a widget only sets the text color for 'text' (loosely defined) elements of the widget itself (e.g. the text label in a checkbox), not what you print yourself. That would be possible, but then I'd have to interfere with all calls at my 'DisplayZone' level.

A window has no text elements itself, so the color setting does noting there...

**Comment by digi-thomas2003** [comment]
Hello Rop,

thanks for your answer.
As I thought over my question and your answer I came to the conclusion that it is good so as it is.
In my window I want to use text with different colors, so it is best to use `setTextColor`

Best regards
Tom
