### ISSUE TITLE
Illegal characters

### ISSUE THREAD

**Issue by vkichline** [M5ez/Core2ez#5]
In `M5Core2.h`, line 122:

```
    #error “This library only supports boards with ESP32 processor.”
```

...the quotes are non-ascii quotes and do not work in the preprocessor context.
When I analyze my project with the PlatformIO static code analyzer, it reports this as:

```
cppcheck	HIGH	ERROR	CWE-0:The code contains unhandled character(s) (character code=226). Neither unicode nor extended ascii is supported.	…M5Core2\src\M5Core2.h:122:0
```

**Comment by ropg** [comment]
But that's not part of this library, right?

**Comment by vkichline** [comment]
Sorry about that! Got the Core2's confused.
